[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server-backend.cjs"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "5001"